name: isar
description: Extremely fast, easy to use, and fully async NoSQL database for Flutter.
version: 4.0.0-dev.14
repository: https://github.com/isar/isar/tree/main/packages/isar
homepage: https://github.com/isar/isar
issue_tracker: https://github.com/isar/isar/issues
documentation: https://isar.dev
funding:
  - https://github.com/sponsors/simc/
topics:
  - database
  - isar
  - sqlite
  - encryption
  - storage

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ">=7.0.0 <9.0.0"
  build: ^3.0.0
  ffi: ">=2.0.0 <3.0.0"
  js: ^0.7.1
  meta: ^1.9.1
  source_gen: ^3.0.0

dev_dependencies:
  ffigen: 19.1.0
  very_good_analysis: ^5.0.0+1
